## Put comments here that give an overall description of what your
## functions do
## First function defines 'subfuntions' to 'read' and 'write' data 
## using an square matrix as argument. Second functions 'decides' if
## needs to do computation or reading operations according the
## information generated by first function.

## Write a short comment describing this function:
## Initially makeCacheMatrix creates an empty matrix, then it defines
## four functions to "write" and "read" the information in x and s
## variables, in "set" kind functions, the values assigned are on an
## superior environment, so they can be used by the CacheSolve funtion.

makeCacheMatrix <- function(x = matrix()) {
  s <- matrix()
  set <- function(y) {
    x <<- y
    s <<- matrix()
  }
  get <- function() x
  setsolve <- function(solve) s <<- solve
  getsolve <- function() s
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}

## Write a short comment describing this function
## cacheSolve function must has as argument makeCacheMatrix
## function, so it can "read" within in if the inverse matrix
## has been calculated already (looking for Nan elements in
## the 'getsolve' data). If the data exists, then there is not
## computation and the data is returned; in the other hand
## the function computes the inverse of the matrix 'stored'
## by 'get' function.

cacheSolve <- function(x, ...) {
  s <- x$getsolve()
  if(!anyNA(s)) {
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setsolve(s)
  s  ## Return a matrix that is the inverse of 'x'
}
